# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon//setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/giza/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/amazon/giza/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/amazon/giza/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/amazon/giza/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/amazon/giza/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/amazon/giza/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/amazon/giza/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/amazon/giza/proprietary/lib/libcam.device3.so:system/lib/libcam.device3.so \
    vendor/amazon/giza/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/amazon/giza/proprietary/lib/libcam.exif.v3.so:system/lib/libcam.exif.v3.so \
    vendor/amazon/giza/proprietary/lib/libcam.hal3a.v3.so:system/lib/libcam.hal3a.v3.so \
    vendor/amazon/giza/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/amazon/giza/proprietary/lib/libcam.iopipe_FrmB.so:system/lib/libcam.iopipe_FrmB.so \
    vendor/amazon/giza/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/amazon/giza/proprietary/lib/libcam.metadataprovider.so:system/lib/libcam.metadataprovider.so \
    vendor/amazon/giza/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/amazon/giza/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/amazon/giza/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/amazon/giza/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/amazon/giza/proprietary/lib/libcam3_app.so:system/lib/libcam3_app.so \
    vendor/amazon/giza/proprietary/lib/libcam3_hwnode.so:system/lib/libcam3_hwnode.so \
    vendor/amazon/giza/proprietary/lib/libcam3_hwpipeline.so:system/lib/libcam3_hwpipeline.so \
    vendor/amazon/giza/proprietary/lib/libcam3_pipeline.so:system/lib/libcam3_pipeline.so \
    vendor/amazon/giza/proprietary/lib/libcam3_utils.so:system/lib/libcam3_utils.so \
    vendor/amazon/giza/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/amazon/giza/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/amazon/giza/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/amazon/giza/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/amazon/giza/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/amazon/giza/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/amazon/giza/proprietary/lib/libcamdrv_FrmB.so:system/lib/libcamdrv_FrmB.so \
    vendor/amazon/giza/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/amazon/giza/proprietary/lib/libfeatureiodrv.so:system/lib/libfeatureiodrv.so \
    vendor/amazon/giza/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/amazon/giza/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/amazon/giza/proprietary/lib/libimageio_FrmB.so:system/lib/libimageio_FrmB.so \
    vendor/amazon/giza/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/amazon/giza/proprietary/lib/libimageio_plat_drv_FrmB.so:system/lib/libimageio_plat_drv_FrmB.so \
    vendor/amazon/giza/proprietary/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    vendor/amazon/giza/proprietary/lib64/lib3a.so:system/lib64/lib3a.so \
    vendor/amazon/giza/proprietary/lib64/libbwc.so:system/lib64/libbwc.so \
    vendor/amazon/giza/proprietary/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    vendor/amazon/giza/proprietary/lib64/libcam.campipe.so:system/lib64/libcam.campipe.so \
    vendor/amazon/giza/proprietary/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    vendor/amazon/giza/proprietary/lib64/libcam.client.so:system/lib64/libcam.client.so \
    vendor/amazon/giza/proprietary/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    vendor/amazon/giza/proprietary/lib64/libcam.device3.so:system/lib64/libcam.device3.so \
    vendor/amazon/giza/proprietary/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    vendor/amazon/giza/proprietary/lib64/libcam.exif.v3.so:system/lib64/libcam.exif.v3.so \
    vendor/amazon/giza/proprietary/lib64/libcam.hal3a.v3.so:system/lib64/libcam.hal3a.v3.so \
    vendor/amazon/giza/proprietary/lib64/libcam.iopipe.so:system/lib64/libcam.iopipe.so \
    vendor/amazon/giza/proprietary/lib64/libcam.iopipe_FrmB.so:system/lib64/libcam.iopipe_FrmB.so \
    vendor/amazon/giza/proprietary/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
    vendor/amazon/giza/proprietary/lib64/libcam.metadataprovider.so:system/lib64/libcam.metadataprovider.so \
    vendor/amazon/giza/proprietary/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    vendor/amazon/giza/proprietary/lib64/libcam.utils.sensorlistener.so:system/lib64/libcam.utils.sensorlistener.so \
    vendor/amazon/giza/proprietary/lib64/libcam.utils.so:system/lib64/libcam.utils.so \
    vendor/amazon/giza/proprietary/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
    vendor/amazon/giza/proprietary/lib64/libcam3_app.so:system/lib64/libcam3_app.so \
    vendor/amazon/giza/proprietary/lib64/libcam3_hwnode.so:system/lib64/libcam3_hwnode.so \
    vendor/amazon/giza/proprietary/lib64/libcam3_hwpipeline.so:system/lib64/libcam3_hwpipeline.so \
    vendor/amazon/giza/proprietary/lib64/libcam3_pipeline.so:system/lib64/libcam3_pipeline.so \
    vendor/amazon/giza/proprietary/lib64/libcam3_utils.so:system/lib64/libcam3_utils.so \
    vendor/amazon/giza/proprietary/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    vendor/amazon/giza/proprietary/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    vendor/amazon/giza/proprietary/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    vendor/amazon/giza/proprietary/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    vendor/amazon/giza/proprietary/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    vendor/amazon/giza/proprietary/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    vendor/amazon/giza/proprietary/lib64/libcamdrv_FrmB.so:system/lib64/libcamdrv_FrmB.so \
    vendor/amazon/giza/proprietary/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
    vendor/amazon/giza/proprietary/lib64/libfeatureiodrv.so:system/lib64/libfeatureiodrv.so \
    vendor/amazon/giza/proprietary/lib64/libfile_op.so:system/lib64/libfile_op.so \
    vendor/amazon/giza/proprietary/lib64/libimageio.so:system/lib64/libimageio.so \
    vendor/amazon/giza/proprietary/lib64/libimageio_FrmB.so:system/lib64/libimageio_FrmB.so \
    vendor/amazon/giza/proprietary/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    vendor/amazon/giza/proprietary/lib64/libimageio_plat_drv_FrmB.so:system/lib64/libimageio_plat_drv_FrmB.so \
    vendor/amazon/giza/proprietary/lib64/libmtkcamera_client.so:system/lib64/libmtkcamera_client.so \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/anlg_dock_headset.csv:system/vendor/smartvolume/giza/anlg_dock_headset.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/aux_digital.csv:system/vendor/smartvolume/giza/aux_digital.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_a2dp.csv:system/vendor/smartvolume/giza/bt_a2dp.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_a2dp_headphones.csv:system/vendor/smartvolume/giza/bt_a2dp_headphones.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_a2dp_speaker.csv:system/vendor/smartvolume/giza/bt_a2dp_speaker.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_sco.csv:system/vendor/smartvolume/giza/bt_sco.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_sco_carkit.csv:system/vendor/smartvolume/giza/bt_sco_carkit.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_sco_headset.csv:system/vendor/smartvolume/giza/bt_sco_headset.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/default.csv:system/vendor/smartvolume/giza/default.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/dgtl_dock_headeset.csv:system/vendor/smartvolume/giza/dgtl_dock_headeset.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/speaker.csv:system/vendor/smartvolume/giza/speaker.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/wired_headphone.csv:system/vendor/smartvolume/giza/wired_headphone.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/wired_headset.csv:system/vendor/smartvolume/giza/wired_headset.csv

PRODUCT_PACKAGES += \
    libcameracustom
