# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon//setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/anlg_dock_headset.csv:system/vendor/smartvolume/giza/anlg_dock_headset.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/aux_digital.csv:system/vendor/smartvolume/giza/aux_digital.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_a2dp.csv:system/vendor/smartvolume/giza/bt_a2dp.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_a2dp_headphones.csv:system/vendor/smartvolume/giza/bt_a2dp_headphones.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_a2dp_speaker.csv:system/vendor/smartvolume/giza/bt_a2dp_speaker.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_sco.csv:system/vendor/smartvolume/giza/bt_sco.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_sco_carkit.csv:system/vendor/smartvolume/giza/bt_sco_carkit.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/bt_sco_headset.csv:system/vendor/smartvolume/giza/bt_sco_headset.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/default.csv:system/vendor/smartvolume/giza/default.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/dgtl_dock_headeset.csv:system/vendor/smartvolume/giza/dgtl_dock_headeset.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/speaker.csv:system/vendor/smartvolume/giza/speaker.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/wired_headphone.csv:system/vendor/smartvolume/giza/wired_headphone.csv \
    vendor/amazon/giza/proprietary/vendor/smartvolume/giza/wired_headset.csv:system/vendor/smartvolume/giza/wired_headset.csv
